In [105]:
import os
import numpy as np
from PIL import Image
from sklearn import metrics
import matplotlib.pyplot as plt
from scipy.ndimage import convolve
from skimage.transform import resize
from sklearn.pipeline import Pipeline
from sklearn.neural_network import BernoulliRBM
from skimage.io import imread_collection, imshow
from sklearn.linear_model import LogisticRegression

In [106]:
imgs = imread_collection('centered/*.gif')
imgs = [resize(x,(77,65),mode='constant', anti_aliasing=False) for x in imgs]
imgsarr = [x.flatten('C') for x in imgs]
y = [[_ for i in range(1,12)] for _ in range(1,16)]
y = [num for sub in Y for num in sub]

In [107]:
rbm = BernoulliRBM(random_state=0,verbose=True,learning_rate=.01,n_iter=20,n_components=150)
logistic = LogisticRegression(solver='lbfgs', multi_class='multinomial')
rbm_features_classifier = Pipeline(steps=[('rbm', rbm), ('logistic', logistic)])
rbm_features_classifier.fit(imgsarr, Y)

[BernoulliRBM] Iteration 1, pseudo-likelihood = -2859.07, time = 0.23s
[BernoulliRBM] Iteration 2, pseudo-likelihood = -3044.42, time = 0.26s
[BernoulliRBM] Iteration 3, pseudo-likelihood = -2666.64, time = 0.24s
[BernoulliRBM] Iteration 4, pseudo-likelihood = -2527.39, time = 0.24s
[BernoulliRBM] Iteration 5, pseudo-likelihood = -2475.21, time = 0.24s
[BernoulliRBM] Iteration 6, pseudo-likelihood = -2468.15, time = 0.24s
[BernoulliRBM] Iteration 7, pseudo-likelihood = -2482.79, time = 0.25s
[BernoulliRBM] Iteration 8, pseudo-likelihood = -2466.78, time = 0.25s
[BernoulliRBM] Iteration 9, pseudo-likelihood = -2459.73, time = 0.24s
[BernoulliRBM] Iteration 10, pseudo-likelihood = -2439.38, time = 0.24s
[BernoulliRBM] Iteration 11, pseudo-likelihood = -2472.61, time = 0.24s
[BernoulliRBM] Iteration 12, pseudo-likelihood = -2447.53, time = 0.24s
[BernoulliRBM] Iteration 13, pseudo-likelihood = -2410.22, time = 0.25s
[BernoulliRBM] Iteration 14, pseudo-likelihood = -2439.37, time = 0.24s
[

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


Pipeline(memory=None,
     steps=[('rbm', BernoulliRBM(batch_size=10, learning_rate=0.01, n_components=150, n_iter=20,
       random_state=0, verbose=True)), ('logistic', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False))])

In [112]:
Y_pred = rbm_features_classifier.predict(imgsarr)
print(metrics.confusion_matrix(y,Y_pred))
print("Logistic regression w/ RBM:\n",metrics.classification_report(Y, Y_pred))

[[ 8  0  0  0  0  0  0  1  0  0  0  2  0  0  0]
 [ 0  8  2  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  3  3  0  0  0  1  0  1  0  0  0  1  0  2]
 [ 0  0  0 10  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0  1  0  0  0]
 [ 0  1  1  0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  9  0  0  1  0  0  0  0  1]
 [ 3  2  0  0  1  1  0  0  2  0  0  0  1  0  1]
 [ 5  0  0  1  1  0  0  0  3  0  0  1  0  0  0]
 [ 0  0  0  0  0  1  1  0  0  6  1  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0  0]
 [ 1  0  0  0  4  0  0  0  1  0  0  5  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  1  0  9  0  0]
 [ 0  0  0  0  1  0  0  0  2  0  1  1  0  6  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0  0 10]]
Logistic regression w/ RBM:
               precision    recall  f1-score   support

           1       0.47      0.73      0.57        11
           2       0.57      0.73      0.64        11
           3       0.43      0.27      0.33        11
           4       0.91      0.91